### PR TITLE
Implementation of initial live code swapping

### PR DESCRIPTION
**Pull request by Gozala**
[react-hot-loader](https://gaearon.github.io/react-hot-loader/) is a popular tool in react community that enables developers to apply code edits on the running app without reload. While this is useful on it's own it's a foundation for working with transaction-monitor (see #663 for details) that allows you to record session and then replay each step, with live code swapping you can fix a bug and reply steps to make sure it's fixed.

Now current setup uses [livereactload](https://github.com/milankinen/livereactload) which is clone of [react-hot-loader](https://gaearon.github.io/react-hot-loader/) for [browserify](http://browserify.org) instead of [webpack](http://webpack.github.io) which I chose to use because:

1. We already used browserify for doing builds so it's was easier to integrate.
2. Unfortunately react-hot-loader did not worked for us out the box as some of the assumption it makes were not valid in our setup.

Ultimately I think switch to react-hot-loader and webpack would be beneficial as unlike livereactload react-hot-loader can update individual modules rather than whole bundle so it's going to be a lot faster.

## Known limitations / issues

1. iframes are reloaded when code is swapped (Caused by react issue facebook/react#4826)
2. changes to about:settings do not cause code swap. This is actually intentional since just reloading `about:settings` page seems good enough.

## Usage

Currently to use this you need to run `npm run live` or if you just interested in server and not a client you can run `npm run live-server`. Please note that we need to have eval to enable hot swapping there for `.profile/user.js` file was added to enable eval for development. If you run client separately make sure to use profile that will have a similar setup.

### CODE REVIEW

**Comment by Gozala** [comment]
This also fixes #644

**Comment by gordonbrander** [comment]
If we need eval, how will this work in Graphene?

**Comment by paulrouget** [comment]
Because it's only for development, we can allow eval.

**Comment by Gozala** [comment]
> If we need eval, how will this work in Graphene?

As @paulrouget said it's only enabled for development so code can be live reloaded. Live reloading is not part of the deployment build so no eval is required there.

**Comment by gordonbrander** [comment]
Looks like we don't watch for changes to the CSS directory. We probably should, right?

**Comment by gordonbrander** [comment]
Other than that, looks good.

**Comment by Gozala** [comment]
> Looks like we don't watch for changes to the CSS directory. We probably should, right?

We should probably just kill css directory. Either way live reload knows how to hot swap js code it can't really do anything with css. We could teach it how to swap css as well but I don't think it's worth it given that it's almost not used.

**Comment by gordonbrander** [comment]
Ok, wfm.

**Pull request merged**
