### PR TITLE
Retain selected suggestion across suggestion updates.

### PR DESCRIPTION
**Pull request by Gozala**
Fix for #623

### CODE REVIEW

**Comment by Gozala** [comment]
- [ ] Need to increment a version as db model has changed.

**Comment by gordonbrander** [comment]
Interaction bug:

- Arrow down to top hit
- Select all (cmd a) and then start typing

What should happen: blow away old text and insert new text.
What happens: the url of the top hit stays in the input even as you type. Cursor jumps around.

**Comment by gordonbrander** [comment]
Apparently it works this way in master. @Gozala to file a bug for it.

**Comment by gordonbrander** [comment]
R+. @Gozala can you bump the db model version and then merge?

**Pull request merged**
