### PR TITLE
add more tiles

### PR DESCRIPTION
**Pull request by PalmerAL**

### CODE REVIEW

**Comment by gordonbrander** [comment]
`tiles/live.com.png` this is the Outlook logo, not the Live logo. Does Live have a logo? I'm not sure...

**Comment by gordonbrander** [comment]
Everything else looks great. Thanks for working on this!

**Comment by PalmerAL** [comment]
Live.com just gives you the login page and logo for outlook web app.

**Comment by gordonbrander** [comment]
Works for me.

**Pull request merged**
