### PR TITLE
Fix jscs validation errors

### PR DESCRIPTION
**Pull request by KevinGrandon**
This is kind of funny. We've moved the JS into node_modules, but we're currently ignoring all style checks in the node_modules folder: https://github.com/mozilla/browser.html/blob/master/.jscsrc#L4

This fixes most of the style validation. We still ignore errors, but that will be fixed once we land #75 (or we could update the paths in .jscsrc).

### CODE REVIEW

**Comment by Gozala** [comment]
@KevinGrandon is there any way we could configure `jscs` to not require indentation for the wrapper function body ? I do plan to get rid of those wrappers soonish & would really like to avoid making complete reindent commits, that's why function wrapper body isn't indented in first place.

**Comment by gordonbrander** [comment]
+1 I would prefer to fix the linter

**Comment by KevinGrandon** [comment]
I don't really think it's worth it to be scared of indentation changes, there's not a ton of code :)

If we're not ready to migrate to another solution (not sure what you had in mind), then I'll see what options jscs has, I've never used it before. Switching to jshint might also work - jshint is more about syntax and less about style.

**Comment by gordonbrander** [comment]
If we're going to do this, let's merge outstanding PRs that touch many files like https://github.com/mozilla/browser.html/pull/93 first. I've already re-written that one once with all the file reorganizations ;)

**Comment by paulrouget** [comment]
Agreed with Kevin. Let's fix indentation in the code. Code base is pretty small today. And to be honest, the current indentation drives me nuts :)

**Comment by paulrouget** [comment]
Sorry, I short-circuited you with PR #101

**Comment by KevinGrandon** [comment]
> Sorry, I short-circuited you with PR #101

This is fine and well, but does make it a bit de-motivating to potential contributors. If you are looking for contributors for the project I suggest you stop doing that in the future. (I'll still do stuff if I have time)

**Pull request closed without merging**
