### PR TITLE
Add CSS snap points

### LINKED ISSUE #55: Use scrollgrab & scroll snapping to implement toolbar animation
The body of the app should overflow: toolbar (50px) + iframes (100vh). The body should use scrollgrab and scroll snapping to hide/show the toolbar.

Scroll-position based animations could be used to animate the opacity of the bar.

This requires some platform work. First step is to get scrollgrab to work on desktop. So far, I'm blocked because of https://bugzilla.mozilla.org/show_bug.cgi?id=1124099

### PR DESCRIPTION
**Pull request by paulrouget**
Introducing snap points. More work is required for scroll operations not triggered by the wheel.
Resolves #55.

### CODE REVIEW

**Comment by paulrouget** [comment]
(requires patches from bug 945584)

**Comment by paulrouget** [comment]
@gordonbrander can you review this?

**Comment by paulrouget** [comment]
There's a weird behavior where the navbar covers the content when it snaps back to `0 0`. Ignore this, it's a scroll *grab* issue when APZC is not enabled.

**Comment by gordonbrander** [comment]
Code is fine. This feels so much better... MERGE ASAP!

**Pull request merged**
