### PR TITLE
Fix flickering scrollbars #193

### PR DESCRIPTION
**Pull request by Gozala**
Workaround for #193

### CODE REVIEW

**Comment by gordonbrander** [comment]
This fix does not work for me (checked out branch, reset session, refreshed browser, restarted browser, loaded facebook.com). I still get the flickering scrollbar.

**Comment by gordonbrander** [comment]
NVM, this was human error when checking out the branch. Sorry for the false alarm.

**Comment by paulrouget** [comment]
Why do you use an undefined value? Set it to `false` by default and only allow it to go from `false` to `true`. With this setting, you only listen to the first event. We should only allow one toggling.

We want this to work: `no overflow -> no overflow -> overflow`.

**Comment by paulrouget** [comment]
See #353

**Pull request merged**
