### PR TITLE
Kill flexbox model

### PR DESCRIPTION
**Pull request by paulrouget**
to review

### CODE REVIEW

**Comment by paulrouget** [comment]
One of the issue I'm running into is the `order:n` property that is only support with the flex box model. Instead of trying to fix this, I'd prefer to remove the tab re-ordering. Any objection?

**Comment by paulrouget** [comment]
Not for self: next, fix *fixmes*, then fix *order*, then merge.

**Comment by paulrouget** [comment]
@Gozala can you please take a look at this?

I removed flexbox for everything except the dashboard and the tabstrip element (because of `order:n`).
I also moved some CSS code to JS.

**Comment by gordonbrander** [comment]
Did a pretty thorough QA and can't find any bugs with the implementation. Going through the code now.

**Comment by gordonbrander** [comment]
Note that this doesn't cover `dashboard.css`. OK with me. Better to do that in a separate commit.

**Pull request merged**
